#!/usr/bin/env python3
"""Generate src/proto_params.vh from config/arch.yaml.

The YAML used here is intentionally flat (key: integer), so this generator has
no external Python dependency.  That keeps architecture changes reproducible
without making the Tiny Tapeout synthesis flow depend on PyYAML.
"""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
ARCH = ROOT / "config" / "arch.yaml"
OUT = ROOT / "src" / "proto_params.vh"


def parse_flat_yaml(path: Path):
    cfg = {}
    for lineno, raw in enumerate(path.read_text().splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        if ":" not in line:
            raise ValueError(f"{path}:{lineno}: expected key: value")
        key, value = [x.strip() for x in line.split(":", 1)]
        try:
            cfg[key] = int(value, 0)
        except ValueError as exc:
            raise ValueError(f"{path}:{lineno}: value must be an integer") from exc
    return cfg


cfg = parse_flat_yaml(ARCH)
required = [
    "instr_width", "data_width", "gpio_width", "shift_width", "tick_width",
    "imem_addr_width", "imem_depth", "fifo_depth", "cfg_addr_width", "cfg_count",
]
missing = [k for k in required if k not in cfg]
if missing:
    raise SystemExit("Missing architecture keys: " + ", ".join(missing))

# V0 ISA assumptions.  If one of these changes, the RTL/ISA itself must change,
# not merely the build parameters.
if cfg["instr_width"] != 16:
    raise SystemExit("V0 ISA requires instr_width: 16")
if cfg["data_width"] != 8:
    raise SystemExit("V0 ISA/register format requires data_width: 8")
if cfg["gpio_width"] != 8:
    raise SystemExit("V0 pin selectors require gpio_width: 8")
if cfg["shift_width"] != cfg["data_width"]:
    raise SystemExit("V0 requires shift_width == data_width")
if cfg["cfg_addr_width"] != 3 or cfg["cfg_count"] != 8:
    raise SystemExit("V0 CFG encoding requires 3-bit address / 8 config bytes")
if cfg["imem_depth"] != (1 << cfg["imem_addr_width"]):
    raise SystemExit("imem_depth must equal 2**imem_addr_width in V0")
if cfg["fifo_depth"] < 2:
    raise SystemExit("fifo_depth must be >= 2")

names = [
    ("PROTO_INSTR_W", "instr_width"),
    ("PROTO_DATA_W", "data_width"),
    ("PROTO_GPIO_W", "gpio_width"),
    ("PROTO_SHIFT_W", "shift_width"),
    ("PROTO_TICK_W", "tick_width"),
    ("PROTO_IMEM_AW", "imem_addr_width"),
    ("PROTO_IMEM_DEPTH", "imem_depth"),
    ("PROTO_FIFO_DEPTH", "fifo_depth"),
    ("PROTO_CFG_AW", "cfg_addr_width"),
    ("PROTO_CFG_COUNT", "cfg_count"),
]

lines = [
    "`ifndef PROTO_PARAMS_VH",
    "`define PROTO_PARAMS_VH",
    "",
    "// AUTO-GENERATED by tools/gen_params.py from config/arch.yaml.",
    "// Do not edit this file directly.",
    "",
]
for macro, key in names:
    lines.append(f"`define {macro:<18} {cfg[key]}")
lines += ["", "`endif", ""]
OUT.write_text("\n".join(lines))
print(f"Generated {OUT.relative_to(ROOT)}")
