`ifndef PROTO_PARAMS_VH
`define PROTO_PARAMS_VH

// AUTO-GENERATED by tools/gen_params.py from config/arch.yaml.
// Do not edit this file directly.

`define PROTO_INSTR_W      16
`define PROTO_DATA_W       8
`define PROTO_GPIO_W       8
`define PROTO_SHIFT_W      8
`define PROTO_TICK_W       16
`define PROTO_IMEM_AW      8
`define PROTO_IMEM_DEPTH   256
`define PROTO_FIFO_DEPTH   4
`define PROTO_CFG_AW       3
`define PROTO_CFG_COUNT    8

`endif
